# Generated by Django 4.2.4 on 2023-09-21 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('content', models.TextField(max_length=2000, verbose_name='текст статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='изображение')),
                ('number_of_views', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('date_of_publication', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('owner', models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('number_of_views', 'date_of_publication'),
            },
        ),
    ]
