# Generated by Django 4.2.4 on 2023-09-19 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='контактный email')),
                ('surname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество (если есть)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(verbose_name='время рассылки')),
                ('mailing_frequency', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=50, verbose_name='периодичность рассылки')),
                ('mailing_status', models.CharField(choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], default='создана', max_length=50, verbose_name='статус рассылки')),
                ('clients', models.ManyToManyField(related_name='mailings', to='management_service.client')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_subject', models.TextField(verbose_name='тема сообщения')),
                ('message_text', models.TextField(verbose_name='текст сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_date_time', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('attempt_status', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], max_length=50, verbose_name='статус попытки')),
                ('mail_server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера (если был)')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_logs', to='management_service.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_service.message', verbose_name='сообщение'),
        ),
    ]
