# Generated by Django 4.2.4 on 2023-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_service', '0002_mailing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(related_name='mailings', to='management_service.client', verbose_name='клиенты'),
        ),
    ]
